backend:
  name: github
  repo: UltraYield/docs # Path to your GitHub repository
  open_authoring: true

public_folder: ".vitepress/dist"
media_folder: "public"

collections:
  - name: "navigation"
    label: "Навигация"
    folder: "nav"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "text", widget: "string" }
      - { label: "URL", name: "link", widget: "string" }
      - { label: "Порядок", name: "order", widget: "number" }
  - name: "sidebar"
    label: "Боковое меню"
    folder: "sidebar"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "text", widget: "string" }
      - { label: "URL", name: "link", widget: "string" }
      - { label: "Порядок", name: "order", widget: "number" }
  - name: "features"
    label: "Детали"
    folder: "features"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "text", widget: "string" }
      - { label: "Описание", name: "description", widget: "markdown" }
